name: flutter_im
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.2.0
  flutter_inappwebview: ^5.7.2+3
  qr_flutter: ^4.1.0
  flutter_easy_permission: ^1.1.2
  flutter_scankit: ^1.2.4
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: aliIcon
      fonts: 
        - asset: lib/assets/icons/iconfont.ttf
  
  assets:
    - lib/assets/img/
