name: tencent_mi_flutter
version: 1.0.0+1
publish_to: none
description: 基于腾讯IM
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  kumi_popup_window: ^2.0.1
  tencent_cloud_chat_sdk: ^5.1.7
  tencent_im_sdk_plugin_desktop: ^0.1.19
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

